version: "3"

services:
  tm_bot:
    container_name: tm_bot
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - ./static:/usr/src/app/static
    ports:
      - "8000:8000"
