# Generated by Django 4.0 on 2021-12-29 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Tariff",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date_create",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Время создания"
                    ),
                ),
                (
                    "date_update",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Время последнего изменения"
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=255, verbose_name="Заголовок тарифа"),
                ),
                ("description", models.TextField(verbose_name="Описание тарифа")),
                ("price", models.PositiveIntegerField(verbose_name="Цена тарифа")),
                (
                    "position",
                    models.PositiveIntegerField(verbose_name="Позиция в списке"),
                ),
                ("enable", models.BooleanField(default=True, verbose_name="Активен")),
            ],
            options={
                "verbose_name": "Тариф",
                "verbose_name_plural": "Тарифы",
                "db_table": "tariff",
            },
        ),
    ]
