# Generated by Django 4.0 on 2021-12-29 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Guest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date_create",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Время создания"
                    ),
                ),
                (
                    "date_update",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Время последнего изменения"
                    ),
                ),
                (
                    "first_name",
                    models.CharField(max_length=64, verbose_name="Имя гостя"),
                ),
                (
                    "last_name",
                    models.CharField(max_length=64, verbose_name="Фамилия гостя"),
                ),
                (
                    "username",
                    models.CharField(
                        max_length=64, unique=True, verbose_name="Логин гостя"
                    ),
                ),
            ],
            options={
                "verbose_name": "Гость",
                "verbose_name_plural": "Гости",
                "db_table": "bot_guest",
            },
        ),
        migrations.AlterField(
            model_name="tariff",
            name="position",
            field=models.PositiveIntegerField(
                unique=True, verbose_name="Позиция в списке"
            ),
        ),
    ]
