# Generated by Django 4.0 on 2021-12-29 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_alter_guest_first_name_alter_guest_last_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="guest",
            name="date_create",
            field=models.DateTimeField(
                auto_now_add=True, null=True, verbose_name="Время создания"
            ),
        ),
        migrations.AlterField(
            model_name="guest",
            name="date_update",
            field=models.DateTimeField(
                auto_now=True, null=True, verbose_name="Время последнего изменения"
            ),
        ),
        migrations.AlterField(
            model_name="tariff",
            name="date_create",
            field=models.DateTimeField(
                auto_now_add=True, null=True, verbose_name="Время создания"
            ),
        ),
        migrations.AlterField(
            model_name="tariff",
            name="date_update",
            field=models.DateTimeField(
                auto_now=True, null=True, verbose_name="Время последнего изменения"
            ),
        ),
    ]
